name: Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  publish-library:
    name: Publish package to PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: pdm-project/setup-pdm@v4
        name: Setup Python and PDM
        with:
          python-version: "3.12"
          cache: true

      - name: Publish to PyPI
        run: pdm publish
